In [66]:
def cod_sencilla():
    alfabeto = {'A':4,'B':13,'C':26,'D':12,'E':3,'F':17,'G':6,'H':14,'I':5,'J':25,'K':30,'L':7,'M':11,'N':20,'O':10,'P':19,'Q':24,'R':18,'S':15,'T':9,'U':0,'V':16,'W':21,'X':2,'Y':8,'Z':22,'Ñ':1}
    print("inserta una palabra o frase de 9 letras:")
    palabra = input()
    palabra = palabra.upper().replace(" ","")
    B0 = []
    for x in palabra:
        B0.append(alfabeto[x])
    print(f"Tu mensaje codificado es:", *B0)
    return B0
    

In [67]:
B_s =cod_sencilla()

inserta una palabra o frase de 9 letras:
tu ex es fea
Tu mensaje codificado es: 9 0 3 2 3 15 17 3 4


In [68]:
import numpy as np 
def creacion_B(simple):
    B = np.array([[B_s[0],B_s[3],B_s[6]],[B_s[1],B_s[4],B_s[7]],[B_s[2],B_s[5],B_s[8]]])
    print('La matriz cuadrada de tu codificacion sencilla es:')
    print(B)
    return B

In [69]:
B = creacion_B(B_s)

La matriz cuadrada de tu codificacion sencilla es:
[[ 9  2 17]
 [ 0  3  3]
 [ 3 15  4]]


In [70]:
def codificador(B):
    A = np.array([[1,2,1],[2,5,3],[2,3,2]])
    cod = np.dot(A,B)
    print("La codificacion de tu matriz ha sido reforzada al ser multiplicada por:")
    print(A)
    print("Tu matriz codificada resultante de AB es:")
    print(cod)
    return cod

In [71]:
Bcod = codificador(B)

La codificacion de tu matriz ha sido reforzada al ser multiplicada por:
[[1 2 1]
 [2 5 3]
 [2 3 2]]
Tu matriz codificada resultante de AB es:
[[12 23 27]
 [27 64 61]
 [24 43 51]]


In [77]:
def decodificador(codificado):
    A_1 = np.array([[1,-1,1],[2,0,-1],[-4,1,1]])
    dec = np.dot(A_1,codificado)
    print("Para decodificar tu matriz se multiplicara por la inversa de A:")
    print(A_1)
    print("Tu matriz resultante B1 que debe ser igual que B:")
    print(dec)
    return dec
    

In [78]:
B1 = decodificador(Bcod)

Para decodificar tu matriz se multiplicara por la inversa de A:
[[ 1 -1  1]
 [ 2  0 -1]
 [-4  1  1]]
Tu matriz resultante B1 que debe ser igual que B:
[[ 9  2 17]
 [ 0  3  3]
 [ 3 15  4]]


In [86]:
def regresador(decodificado):
    n_alfabeto = {4:'A',13:'B',26:'C',12:'D',3:'E',17:'F',6:'G',14:'H',5:'I',25:'J',30:'K',7:'L',11:'M',20:'N',10:'O',19:'P',24:'Q',18:'R',15:'S',9:'T',0:'U',16:'V',21:'W',2:'X',8:'Y',22:'Z',1:'Ñ'}
    final = []
    for x in range(3):
        for a in decodificado[:,x]:
            final.append(n_alfabeto[a])
    print(f"Tu mensaje decodificado y original sin espacios y en mayusculas es:", *final)

In [87]:
regresador(B1)

Tu mensaje decodificado y original sin espacios y en mayusculas es: T U E X E S F E A
